name: OWASP ZAP Security Scan

on:
  push:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan with OWASP ZAP
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          # We will scan the file directly from the runner's local filesystem
          target: 'index.html'