name: OWASP ZAP Security Scan

on:
  push:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan with OWASP ZAP
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start local web server
        # Use Python's built-in server to host the files in the background.
        # This makes our index.html available at http://localhost:8000
        run: python -m http.server 8000 &

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          # Scan the URL of the server we just started
          target: 'http://localhost:8000'