name: SonarCloud Security Scan

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # SonarCloud needs a full history to analyze

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          # All parameters are passed as environment variables
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_PROJECT_KEY: githubabhay2003_codtech-task4-devsecops
          SONAR_ORGANIZATION: githubabhay2003