name: OWASP ZAP Security Scan

on:
  push:
    branches: [ "main" ]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan with OWASP ZAP
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          # Use the 'file://' protocol and the absolute path to the workspace
          # This tells ZAP exactly where to find the file on the runner.
          target: 'file://${{ github.workspace }}/index.html'