name: SonarCloud Security Scan

on:
  push:
    branches: [ "main" ]

jobs:
  sonar-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          # The 'with' block must be at the same indentation level as 'env'
          projectKey: githubabhay2003_codtech-task4-devsecops
          organization: githubabhay2003